-- Add host-related columns if they don't exist
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "avatar" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isHost" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hostName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hostBio" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hostVerified" BOOLEAN NOT NULL DEFAULT false;
