export type EventCategory = 'Run Club' | 'Meetup' | 'Workshop' | 'Dinner Club' | 'Book Club' | 'Fitness' | 'Social';

export interface MockEvent {
  id: string;
  title: string;
  category: EventCategory;
  host: {
    name: string;
    initials: string;
    verified: boolean;
    superhost?: boolean;
    newHost?: boolean;
  };
  date: string;
  dateShort: string;
  time: string;
  location: string;
  city: string;
  price: number | 'Free';
  spots: number;
  spotsLeft: number;
  going: number;
  image: string;
  tags: string[];
  featured?: boolean;
}

export const mockEvents: MockEvent[] = [
  {
    id: 'evt-001',
    title: 'Sunday Run Club at Lodhi Garden',
    category: 'Run Club',
    host: { name: 'Arjun Mehta', initials: 'AM', verified: true, superhost: true },
    date: 'Sunday, 24 Nov 2024',
    dateShort: 'Sun 24 Nov',
    time: '6:30 AM',
    location: 'Lodhi Garden, Gate 2',
    city: 'Delhi',
    price: 'Free',
    spots: 30,
    spotsLeft: 6,
    going: 24,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=560&fit=crop&q=80',
    tags: ['Outdoor', 'Beginner-friendly', '5K'],
    featured: true,
  },
  {
    id: 'evt-002',
    title: 'Creator Coffee Meetup at Blue Tokai',
    category: 'Meetup',
    host: { name: 'Priya Sharma', initials: 'PS', verified: true },
    date: 'Saturday, 23 Nov 2024',
    dateShort: 'Sat 23 Nov',
    time: '11:00 AM',
    location: 'Blue Tokai, Lodhi Colony',
    city: 'Delhi',
    price: 299,
    spots: 20,
    spotsLeft: 8,
    going: 12,
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=560&fit=crop&q=80',
    tags: ['Networking', 'Creators', 'Coffee'],
  },
  {
    id: 'evt-003',
    title: 'Brand Strategy Workshop — Build Your Narrative',
    category: 'Workshop',
    host: { name: 'Kavya Nair', initials: 'KN', verified: true, superhost: true },
    date: 'Sunday, 24 Nov 2024',
    dateShort: 'Sun 24 Nov',
    time: '2:00 PM',
    location: 'The Hive, Koramangala',
    city: 'Bangalore',
    price: 999,
    spots: 25,
    spotsLeft: 12,
    going: 13,
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=560&fit=crop&q=80',
    tags: ['Strategy', 'Branding', 'Founders'],
  },
  {
    id: 'evt-004',
    title: 'Founders Dinner at The Bombay Canteen',
    category: 'Dinner Club',
    host: { name: 'Rohan Verma', initials: 'RV', verified: true },
    date: 'Friday, 22 Nov 2024',
    dateShort: 'Fri 22 Nov',
    time: '8:00 PM',
    location: 'The Bombay Canteen, Kamala Mills',
    city: 'Mumbai',
    price: 2499,
    spots: 12,
    spotsLeft: 3,
    going: 9,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=560&fit=crop&q=80',
    tags: ['Startup', 'Curated', 'Invite-style'],
    featured: true,
  },
  {
    id: 'evt-005',
    title: "Book Circle: 'The God of Small Things' at Champaca",
    category: 'Book Club',
    host: { name: 'Ananya Krishnan', initials: 'AK', verified: false, newHost: true },
    date: 'Saturday, 23 Nov 2024',
    dateShort: 'Sat 23 Nov',
    time: '4:00 PM',
    location: 'Champaca Bookstore, Indiranagar',
    city: 'Bangalore',
    price: 'Free',
    spots: 15,
    spotsLeft: 4,
    going: 11,
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=560&fit=crop&q=80',
    tags: ['Literature', 'Discussion', 'Cosy'],
  },
  {
    id: 'evt-006',
    title: 'Trail Run at Sanjay Van — Sunrise Edition',
    category: 'Fitness',
    host: { name: 'Vikram Singh', initials: 'VS', verified: true, superhost: true },
    date: 'Saturday, 23 Nov 2024',
    dateShort: 'Sat 23 Nov',
    time: '5:45 AM',
    location: 'Sanjay Van, Qutub Minar Gate',
    city: 'Delhi',
    price: 149,
    spots: 40,
    spotsLeft: 18,
    going: 22,
    image: 'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=800&h=560&fit=crop&q=80',
    tags: ['Trail', 'Nature', 'Intermediate'],
  },
  {
    id: 'evt-007',
    title: 'Photography Walk — Bandra Lanes',
    category: 'Meetup',
    host: { name: 'Meera Joshi', initials: 'MJ', verified: false, newHost: true },
    date: 'Sunday, 24 Nov 2024',
    dateShort: 'Sun 24 Nov',
    time: '7:00 AM',
    location: 'Bandra Bandstand, Mumbai',
    city: 'Mumbai',
    price: 199,
    spots: 18,
    spotsLeft: 9,
    going: 9,
    image: 'https://images.unsplash.com/photo-1520390138845-fd2d229dd553?w=800&h=560&fit=crop&q=80',
    tags: ['Photography', 'Street Art', 'Creative'],
  },
  {
    id: 'evt-008',
    title: 'Natural Wine & Design Workshop',
    category: 'Workshop',
    host: { name: 'Dev Kapoor', initials: 'DK', verified: true },
    date: 'Friday, 22 Nov 2024',
    dateShort: 'Fri 22 Nov',
    time: '7:00 PM',
    location: 'Kitsch Mandi, Hauz Khas',
    city: 'Delhi',
    price: 1499,
    spots: 20,
    spotsLeft: 7,
    going: 13,
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&h=560&fit=crop&q=80',
    tags: ['Design', 'Wine', 'Creative'],
  },
  {
    id: 'evt-009',
    title: 'Morning Yoga & Breathwork at Cubbon Park',
    category: 'Fitness',
    host: { name: 'Shruti Rao', initials: 'SR', verified: true, superhost: true },
    date: 'Saturday, 23 Nov 2024',
    dateShort: 'Sat 23 Nov',
    time: '6:00 AM',
    location: 'Cubbon Park, Main Lawn',
    city: 'Bangalore',
    price: 'Free',
    spots: 35,
    spotsLeft: 14,
    going: 21,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=560&fit=crop&q=80',
    tags: ['Yoga', 'Wellness', 'Outdoor'],
  },
  {
    id: 'evt-010',
    title: 'Standup Comedy Open Mic — Works in Progress',
    category: 'Social',
    host: { name: 'Kabir Das', initials: 'KD', verified: false },
    date: 'Thursday, 21 Nov 2024',
    dateShort: 'Thu 21 Nov',
    time: '8:30 PM',
    location: 'Canvas Laugh Club, Lower Parel',
    city: 'Mumbai',
    price: 499,
    spots: 60,
    spotsLeft: 22,
    going: 38,
    image: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800&h=560&fit=crop&q=80',
    tags: ['Comedy', 'Nightlife', 'Casual'],
  },
  {
    id: 'evt-011',
    title: 'Tech Founders Dinner — Zero-to-One Series',
    category: 'Dinner Club',
    host: { name: 'Aditya Kumar', initials: 'AK', verified: true, superhost: true },
    date: 'Thursday, 21 Nov 2024',
    dateShort: 'Thu 21 Nov',
    time: '7:30 PM',
    location: 'Social, Hauz Khas Village',
    city: 'Delhi',
    price: 1999,
    spots: 16,
    spotsLeft: 2,
    going: 14,
    image: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=800&h=560&fit=crop&q=80',
    tags: ['Startup', 'VC', 'Exclusive'],
    featured: true,
  },
  {
    id: 'evt-012',
    title: 'Sunday Run Club at Cubbon Park — 10K Group',
    category: 'Run Club',
    host: { name: 'Nisha Patel', initials: 'NP', verified: true },
    date: 'Sunday, 24 Nov 2024',
    dateShort: 'Sun 24 Nov',
    time: '6:00 AM',
    location: 'Cubbon Park, MG Road Gate',
    city: 'Bangalore',
    price: 'Free',
    spots: 40,
    spotsLeft: 16,
    going: 24,
    image: 'https://images.unsplash.com/photo-1598300188904-6a2f85b0e24e?w=800&h=560&fit=crop&q=80',
    tags: ['Running', '10K', 'Community'],
  },
];

export const CATEGORIES: { label: string; value: string }[] = [
  { label: 'All', value: 'All' },
  { label: 'Run Clubs', value: 'Run Club' },
  { label: 'Creator Meetups', value: 'Meetup' },
  { label: 'Workshops', value: 'Workshop' },
  { label: 'Dinners', value: 'Dinner Club' },
  { label: 'Book Clubs', value: 'Book Club' },
  { label: 'Fitness', value: 'Fitness' },
  { label: 'Social', value: 'Social' },
];
